params:
  app: $app
  sdk: $sdk
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget

pipeline:

  build:
    workflow: app/build
    origin:
      URL: ./../
    commands:
      - cd $buildPath/app
      - go get -u .
      - go build -o $app
    download:
      /$buildPath/app/${app}: $releasePath
      /$buildPath/endly/config/config.json: $releasePath

  deploy:
    workflow: app/deploy
    init:
      - mkdir -p $appPath
      - mkdir -p $appPath/config
      - chown -R ${os.user} $appPath
    upload:
      ${releasePath}/${app}: $appPath
      ${releasePath}/config.json: $appPath/config/
    commands:
      - echo 'deployed'

  stop:
    action: process:stop
    input: ${app}

  start:
    action: process:start
    directory:  ${releasePath}/${app}
    immuneToHangups: true
    command: ./${app}
    arguments:
      - "config"
      - "conf/config.json"
      - "-port"
      - "8085"
