init:
  buildPath: /tmp/endly
  version: $TrimSpace($Cat('../../Version'))
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost

defaults:
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost

pipeline:

  buildAll:
    clean:
      action: storage:remove
      assets:
        - URL: ${buildPath}/build
        - URL: ${buildPath}/compact


    mkdir:
      action: exec:run
      commands:
        - mkdir -p  ${buildPath}/compact/usr/lib/
        - mkdir -p  ${buildPath}/compact/usr/local/bin/

    init:
      action: storage:copy
      source: $target
      dest: $target
      assets:
        build: ${buildPath}/build
        compact: ${buildPath}/compact
        'cgo/dep.tar.gz': ${buildPath}/build

    build:
      action: docker:build
      path: ${buildPath}/build/
      arguments:
#        '--no-cache': ''
      tag:
        image: goendly
        version: ${version}-ubuntu16.04

  extract:
    start:
      action: docker:run
      image: goendly:${version}-ubuntu16.04
      name: goendly
      ports:
        "8822": 22

    copy:
      action: docker:copy
      source: $target
      name: goendly
      assets:
        'compact.tar.gz': ${buildPath}/compact/compact.tar.gz
      stopGoEndly:
        action: docker:stop
        name: goendly

  compact:
    build:
      action: docker:build
      path: ${buildPath}/compact/
      arguments:
#        '--no-cache': ''
    tag:
        image: endly
        version: ${version}-ubuntu16.04
 
    tagVersion:
      action: docker:tag
      sourceTag:
        image: endly
        version: ${version}-ubuntu16.04
      targetTag:
        image: endly
        username: endly
        version: ${version}-ubuntu16.04

    tagLatestVersion:
      action: docker:tag
      sourceTag:
        image: endly
        version: ${version}-ubuntu16.04
      targetTag:
        image: endly
        username: endly
        version: latest-ubuntu16.04

    deploy:
      auth:
        action: docker:login
        repository: index.docker.io/endly
        credentials: dockerHubEndly

      pushVersion:
        action: docker:push
        tag:
          image: endly
          username: endly
          version: ${version}-ubuntu16.04

      pushLatestVersion:
        action: docker:push
        tag:
          image: endly
          username: endly
          version: latest-ubuntu16.04


     