init:
  buildPath: /tmp/endly
  version: $TrimSpace($Cat('../../Version'))
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost


pipeline:

  transient:

    clean:
      action: storage:remove
      assets:
        - URL: ${buildPath}/transient
        - URL: ${buildPath}/final

    mkdir:
      action: exec:run
      target: $target
      commands:
        - mkdir -p  ${buildPath}/transient/usr/lib/
        - mkdir -p  ${buildPath}/transient/usr/local/bin/

    init:
      action: storage:copy
      assets:
        transient: ${buildPath}/transient
        final: ${buildPath}/final
        'cgo/dep.tar.gz': ${buildPath}/transient

    build:
      action: docker:build
      path: ${buildPath}/transient/
      nocache: true
      tag:
        image: endly_utransient
        version: ${version}-ubuntu16.04

  extract:
    start:
      action: docker:run
      image: endly_utransient:${version}-ubuntu16.04
      name: endly_utransient
      ports:
        "8822": 22

    copy:
      action: docker:copy
      assets:
        'endly_utransient:/compact.tar.gz': ${buildPath}/final/compact.tar.gz


    cleaup:
      action: docker:remove
      name: endly_utransient


  compact:
    build:
      action: docker:build
      path: ${buildPath}/final
      nocache: true
      tag:
        image: endly
        version: ${version}-ubuntu16.04

    tagVersion:
      action: docker:tag
      sourceTag:
        image: endly
        version: ${version}-ubuntu16.04
      targetTag:
        image: endly
        username: endly
        version: ${version}-ubuntu16.04


    tagLatestVersion:
      action: docker:tag
      sourceTag:
        image: endly
        version: ${version}-ubuntu16.04
      targetTag:
        image: endly
        username: endly
        version: latest-ubuntu16.04


    deploy:
      auth:
        action: docker:login
        repository: index.docker.io/endly
        credentials: dockerHubEndly

      pushVersion:
        action: docker:push
        tag:
          image: endly
          username: endly
          version: ${version}-ubuntu16.04

      pushLatestVersion:
        action: docker:push
        tag:
          image: endly
          username: endly
          version: latest-ubuntu16.04
