init:
  target:
    URL: ssh://127.0.0.1
    Credentials: localhost

pipeline:
  task1:
    action: deployment:deploy
    target: $target
    baseLocation: /use/local/
    appName: tomcat
    version: 7.0
