tasks: $tasks

init:
  buildTarget:
    URL: scp://127.0.0.1/tmp/build/elogger/
    credentials: localhost

  appTarget:
    URL: scp://127.0.0.1/opt/elogger/
    credentials: localhost

  target:
    URL: scp://127.0.0.1/
    credentials: localhost

defaults:
  target: $target

pipeline:


  build:
    checkout:
      action: version/control:checkout
      origin:
        URL: ./../
      dest: $buildTarget
    set-sdk:
      action: sdk:set
      sdk: go:1.12
    build-app:
      action: exec:run
      commands:
        - cd /tmp/build/elogger/app
        - go build elogger.go
        - chmod +x elogger
        -
    deploy:
      mkdir:
        action: exec:run
        commands:
          - sudo rm -rf /opt/elogger/
          - sudo mkdir -p /opt/elogger
          - sudo chown -R ${os.user} /opt/elogger
      install:
        action: storage:copy
        source: $buildTarget
        dest: $appTarget
        expand: true
        assets:
          app/elogger: elogger
          config/config.json: config.json


  stop:
    action: process:stop
    input: elogger

  start:
    action: process:start
    directory: /opt/elogger
    immuneToHangups: true
    command: ./elogger
    arguments:
      - "-config"
      - "config.json"

