init:
  targetHost: 127.0.0.1
  eLoggerHost: ${targetHost}:8777
  target:
    URL: scp://127.0.0.1/
    credentials: localhost
  serviceTarget: $target
  appLogPath: /opt/elogger/logs
  logLocation:
    URL: $appLogPath

defaults:
  app: $app
  sdk: $sdk
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget

pipeline:
  init:
    app:
      action: run
      request: "@app"
      tasks: "*"
  test:
    action: run
    request: '@regression/regression'
    tasks: "*"
  destroy:
    app:
      action: run
      request: "@app"
      tasks: stop
