init:
  app: $app
  sdk: $sdk
  appPath: /opt/${app}
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  serviceTarget: $target
  buildTarget: $target
  appTarget: $target
  targetHost: $Hostname($target.URL)
  appHost: $Hostname($appTarget.URL)
  seleniumServerPort: 8077
  appVersion: 0.1
defaults:
  app: $app
  target: $target
  buildTarget: $buildTarget
  appTarget: $appTarget
pipeline:
  init:
    system:
      action: run
      request: "@system"
      tasks: "*"
    datastore:
      action: run
      request: "@datastore"
      tasks: "*"
    app:
      sdk: $sdk
      action: run
      request: "@app"
      tasks: "*"
  test:
    action: run
    name: regression
    tasks: "*"
  destroy:
    app:
      buildTarget: $target
      app: $app
      appVersion: $appVersion
      action: run
      request: "@app"
      tasks: stop
    system:
        action: run
        request: "@system"
        tasks: destroy
