init:
  data: $Cat('lorem.txt')
  bucket: e2etst

pipeline:
  upload:
    action: storage:upload
    sourceKey: data
    dest:
      URL: gs://$bucket/data/lorem.txt
      credentials: gcp-e2e
  list:
    action: storage:list
    source:
      URL: gs://$bucket/data/
      credentials: gcp-e2e
  download:
    action: storage:download
    source:
      URL: gs://$bucket/data/lorem.txt
      credentials: gcp-e2e
  info:
    action: print
    message: 'Downloaded: $AsString(${download.Payload})'