target: $serviceTarget
name: $name
image: $image
mount:
  "${serviceConfig}": /etc/postgresql/postgresql.conf
ports:
   "5432": "5432"
env:
   POSTGRES_PASSWORD: "**pg**"
   POSTGRES_USER: ##pg##
secrets:
  pg: "$credentials"
