defaults:
  credentials: am
pipeline:
  getInfo:
    action: gc/cloudfunctions:functionsGet
    '@name': projects/abstractmeta-p1/locations/us-central1/functions/function-1
  test:
    action: print
    message: 'TriggerURL: $info.HttpsTrigger.Url'
  callFunction:
    action: gc/cloudfunctions:functionsCall
    '@name': 'projects/abstractmeta-p1/locations/us-central1/functions/function-1'
    callfunctionrequest:
      data:
  printOutput:
    action: print
    message: $callFunction.Result