init:
  buildPath: /tmp/endly
  version: $Cat('../Version')
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost

pipeline:

  init:
    action: storage:copy
    source: $target
    dest: $target
    assets:
      build: ${buildPath}/build
      compact: ${buildPath}/compact


  build:
    action: docker:build
    force: true
    target: $target
    path: ${buildPath}/build/
    tag:
      image: go_endly
      version: $version

  extract:
    start:
      action: docker:run
      target: $target
      image: go_endly:$version
      name: goEndly
      ports:
        "8822": 22

    copy:
      action: docker:copy
      source: $target
      name: goEndly
      assets:

        '/usr/bin/docker':  ${buildPath}/compact/
        '/endly/endly/endly': ${buildPath}/compact/
        '/usr/bin/docker-compose': ${buildPath}/compact/
        '/usr/lib/': ${buildPath}/compact/usr/
        '/usr/lib/python2.7/': ${buildPath}/compact/usr/lib/
        '/usr/lib/libltdl.so.7.3.1':  ${buildPath}/compact/usr/lib/libltdl.so.7
        '/lib/': ${buildPath}/compact/
        '/usr/local/lib/': ${buildPath}/compact/usr/local/

    remove:
      action: storage:remove
      assets:
        - URL: ${buildPath}/compact/usr/lib/gcc/



  compact:
    build:
      action: docker:build
      target: $target
      force: true
      path: ${buildPath}/compact/
      tag:
        image: endly
        version: $version

    start:
      action: docker:run
      target: $target
      image: endly:$version
      mount:
        '/var/run/docker.sock': /var/run/docker.sock
        '${env.HOME}/e2e': /e2e
        '${env.HOME}//secret/': /root/.secret/
      name: endly
      ports:
        "7722": 22
