name: go/web
description: "golang: web hello world"
build: build/go
originurl: "./../"
buildcmd: go build -o $app
docker: false
sdk: go:1.11
dbconfigpath:  datastore
args:
selenium:
  url: http://127.0.0.1:8080/
  in: name
  data: world
  output: output = (#output).text
  assert: output
  submit: run
  expected: Hello world
http:
  request:
    method: get
    url: http://127.0.0.1:8080/
  expect:
    Code: 200
