items:
    asset:
        - name: ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: ID
          indexedby: ""
        - name: LOCATION
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: LOCATION
          indexedby: ""
        - name: DESCRIPTION
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: DESCRIPTION
          indexedby: ""
        - name: WORKFLOW_ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: WORKFLOW_ID
          indexedby: ""
        - name: IS_DIR
          datatype: tinyint
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: IS_DIR
          indexedby: ""
        - name: TEMPLATE
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: TEMPLATE
          indexedby: ""
        - name: INSTANCE_INDEX
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INSTANCE_INDEX
          indexedby: ""
        - name: INSTANCE_TAG
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INSTANCE_TAG
          indexedby: ""
        - name: POSITION
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: POSITION
          indexedby: ""
        - name: FORMAT
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: FORMAT
          indexedby: ""
        - name: CODEC
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: CODEC
          indexedby: ""
    task:
        - name: ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: ID
          indexedby: ""
        - name: WORKFLOW_ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: WORKFLOW_ID
          indexedby: ""
        - name: PARENT_ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: PARENT_ID
          indexedby: ""
        - name: POSITION
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: POSITION
          indexedby: ""
        - name: TAG
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: TAG
          indexedby: ""
        - name: INIT
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INIT
          indexedby: ""
        - name: POST
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: POST
          indexedby: ""
        - name: DESCRIPTION
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: DESCRIPTION
          indexedby: ""
        - name: WHEN_EXPR
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: WHEN_EXPR
          indexedby: ""
        - name: EXIT_EXPR
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: EXIT_EXPR
          indexedby: ""
        - name: ON_ERROR
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: ON_ERROR
          indexedby: ""
        - name: DEFERRED
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: DEFERRED
          indexedby: ""
        - name: SERVICE
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: SERVICE
          indexedby: ""
        - name: ACTION
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: ACTION
          indexedby: ""
        - name: INPUT
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INPUT
          indexedby: ""
        - name: INPUT_URI
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INPUT_URI
          indexedby: ""
        - name: ASYNC
          datatype: tinyint
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: ASYNC
          indexedby: ""
        - name: SKIP_EXPR
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: SKIP_EXPR
          indexedby: ""
        - name: IS_TEMPLATE
          datatype: tinyint
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: IS_TEMPLATE
          indexedby: ""
        - name: SUB_PATH
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: SUB_PATH
          indexedby: ""
        - name: RANGE_EXPR
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: RANGE_EXPR
          indexedby: ""
        - name: DATA
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: DATA
          indexedby: ""
        - name: VARIABLES
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: VARIABLES
          indexedby: ""
        - name: EXTRACTS
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: EXTRACTS
          indexedby: ""
        - name: SLEEP_TIME_MS
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: SLEEP_TIME_MS
          indexedby: ""
        - name: THINK_TIME_MS
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: THINK_TIME_MS
          indexedby: ""
        - name: LOGGING
          datatype: tinyint
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: LOGGING
          indexedby: ""
        - name: REPEAT_RUN
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: REPEAT_RUN
          indexedby: ""
        - name: INSTANCE_INDEX
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INSTANCE_INDEX
          indexedby: ""
        - name: INSTANCE_TAG
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INSTANCE_TAG
          indexedby: ""
    workflow:
        - name: ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: ID
          indexedby: ""
        - name: PARENT_ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: PARENT_ID
          indexedby: ""
        - name: POSITION
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: POSITION
          indexedby: ""
        - name: REVISION
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: REVISION
          indexedby: ""
        - name: URI
          datatype: text
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: URI
          indexedby: ""
        - name: PROJECT_ID
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: PROJECT_ID
          indexedby: ""
        - name: NAME
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: false
          default: ""
          formattag: null
          codec: null
          databasecolumn: NAME
          indexedby: ""
        - name: INIT
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INIT
          indexedby: ""
        - name: POST
          datatype: text
          tag: jsonx:"inline"
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: POST
          indexedby: ""
        - name: TEMPLATE
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: TEMPLATE
          indexedby: ""
        - name: INSTANCE_INDEX
          datatype: int
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INSTANCE_INDEX
          indexedby: ""
        - name: INSTANCE_TAG
          datatype: varchar
          tag: ""
          expression: ""
          filterable: false
          nullable: true
          default: ""
          formattag: null
          codec: null
          databasecolumn: INSTANCE_TAG
          indexedby: ""
modtime: 2024-03-23T09:59:22.888136-07:00
sourceurl: ""
