init:
  '!gcpCredentials': $params.authWith
  gcpSecrets: ${secrets.$gcpCredentials}
  projectID: ${gcpSecrets.ProjectID}


pipeline:
  init-db:
    action: dsunit:init
    datastore: bqtail
    config:
      driverName: bigquery
      credentials: $gcpCredentials
      parameters:
        datasetId: bqtail
    scripts:
      - URL: schema.sql

  patch:
    action: gcp/bigquery:patch
    credentials: $gcpCredentials
    table: ${projectID}:bqtail.dummy
    template: ${projectID}:bqtail.dummy_template

