init:
  appPath: $WorkingDirectory(../..)


pipeline:
  generate:
    action: exec:run
    target: $localhost
    TimeoutMs: 120000
    checkError: true
    commands:
      - cd $appPath
      - export GOPATH=${env.GOPATH}
      - mkdir -p $appPath/.build/plugin/
      - mkdir -p $appPath/repo/Datly/plugin/
      - rm -rf $appPath/.build/plugin/
      - rm -rf $appPath/repo/Datly/plugin/*
      - pwd $appPath
     # - /usr/local/bin/datly gen -o=patch -u=endly/workflow  -s='dql/workflow/workflow_patch.dql' -c='endly|mysql|root:dev@tcp(127.0.0.1:3306)/endly?parseTime=true' -l=go

  #   - /usr/local/bin/datly gen -o=get -u=endly/project  -s='dql/project/project.dql' -c='endly|mysql|root:dev@tcp(127.0.0.1:3306)/endly${qMark}parseTime=true'
      - /usr/local/bin/datly gen -o=get -u=endly/workflow  -s='dql/workflow/workflow.dql' -c='endly|mysql|root:dev@tcp(127.0.0.1:3306)/endly${qMark}parseTime=true'
  #   - /usr/local/bin/datly gen -o=get -u=endly/asset  -s='dql/asset/asset.dql' -c='endly|mysql|root:dev@tcp(127.0.0.1:3306)/endly${qMark}parseTime=true'
  #   - /usr/local/bin/datly gen -o=get -u=endly/task  -s='dql/task/task.dql' -c='endly|mysql|root:dev@tcp(127.0.0.1:3306)/endly${qMark}parseTime=true'


