id: mysql
service: service/mysql
name: MySQL
kind: RDBMS
tag: mysql
version: 5,7
credentials: $mysqlCredentials
config: config/my.cnf
schema: ddl/schema.sql
dictionary: dictionary/
data: data/
sequence: true
tables:
  - dummy
  - dummy_type
