tasks: $tasks

init:
  buildTarget:
    URL: scp://127.0.0.1/tmp/build/reporter/
    credentials: localhost

  appTarget:
    URL: scp://127.0.0.1/opt/reporter/
    credentials: localhost

  target:
    URL: scp://127.0.0.1/
    credentials: localhost

defaults:
  target: $target

pipeline:


  build:
    checkout:
      action: version/control:checkout
      origin:
        URL: ./../
      dest: $buildTarget
    set-sdk:
      action: sdk:set
      sdk: go:1.11
    build-app:
      action: exec:run
      commands:
        - cd /tmp/build/reporter/app
        - go build reporter.go
        - chmod +x reporter
    deploy:
      mkdir:
        action: exec:run
        commands:
          - sudo rm -rf /opt/reporter/
          - sudo mkdir -p /opt/reporter
          - sudo chown -R ${os.user} /opt/reporter

      install:
        action: storage:copy
        source: $buildTarget
        dest: $appTarget
        expand: true
        assets:
          app/reporter: reporter
          config/config.json: config.json


  stop:
    action: process:stop-all
    input: reporter

  start:
    action: process:start
    directory: /opt/reporter
    immuneToHangups: true
    command: ./reporter
    arguments:
      - "-config"
      - "config.json"
      - "-port"
      - "8085"
