init:
  mysqlCredentials: mysql
  target:
    URL: scp://127.0.0.1/
    credentials: localhost

  serviceTarget: $target
  targetHost: 127.0.0.1

pipeline:
  init:
    system:
      action: run
      request: "@system"
      tasks: "*"
    datastore:
      action: run
      request: "@datastore"
      tasks: "*"
    app:
      action: run
      request: "@app"
      tasks: "*"
  test:
    action: run
    request: '@regression/regression'
    tasks: "*"
  destroy:
    app:
      action: run
      request: "@app"
      tasks: stop
    system:
        action: run
        request: "@system"
        tasks: destroy
