tasks: $tasks
init:
  mydb1: ${secrets.${mysqlCredentials}}

pipeline:
  destroy:
    cleanup:
      action: docker:stop
      images:
        - mysql

  init:
    config:
      action: storage:copy
      assets:
        config/my.cnf: /tmp/mydb1.cnf
    services:
      mysql:
        action: docker:run
        image: mysql:5.7
        name: mydb1
        ports:
          3306: 3306
        mount:
          /tmp/mydb1.cnf: /etc/my.cnf
        env:
          MYSQL_ROOT_PASSWORD: ${mydb1.Password}
