pipeline:
  start:
    action: webdriver:start
    target: $target
  open:
    action: webdriver:open
    remoteSelenium:
      URL: http://${targetHost}:$seleniumServerPort/

post:
  - SeleniumSessionID = ${open.SessionID}
