name: default
description: external application URL
build: build/default
docker: true
usesdkbuild: true
dbconfigpath:  datastore
dependency: ""
assets:
args:
selenium:
  url: http://127.0.0.1:8080/form.html
  in: id
  data: 111111
  output: out = (#output).text
  assert: out
  submit: submit
  expected: Please choose a dummy name
http:
  request:
    method: get
    url: http://127.0.0.1:8080/
  expect:
    Code: 200
rest:
  method: get
  url: http://127.0.0.1:8080/
  expect:
    Data:
      Name: name 9999
