pipeline:
  set_sdk:
    multiAction: true
    set_jdk:
      action: sdk:set
      sdk: $sdk
    set_build_runner:
      action: deployment:deploy
      appName: maven
      version: 3.5
    set_env:
      action: exec:run
      commands:
        - echo 'setting env'
  checkout:
    action: version/control:checkout
    origin:
      URL: $originURL
    dest:
      URL: $appPath

  build:
    action: exec:run
    commands:
      - echo 'building app'
      - cd $appPath
      - echo 'mvn clean test'
