defaults:
  credentials: am
pipeline:
  deploy:
    when: false
    action: gcp/cloudfunctions:deploy
    '@name': HelloWorld
    entryPoint: HelloWorld
    runtime: go111
    source:
      URL: test/hello.zip

