tasks: $tasks
defaults:
  app: $app
  version: $version
  sdk: $sdk
pipeline:
  build:
    workflow: app/docker/build
    origin:
      URL: https://github.com/adrianwit/echo
    commands:
      - apt-get -y install telnet
      - cd $buildPath/app
      - go get -u .
      - export CGO_ENABLED=0
      - go build -o $app
      - chmod +x $app
    download:
      /$buildPath/${app}: $releasePath
  stop:
    target: $target
    action: docker:stop-images
    images:
    - echo
  deploy:
    workflow: app/docker/deploy
    name: testApp
    ports:
      "8080": "8080"
