init: "@var/init"

params:
  registryUsername: endly
  registry: index.docker.io/endly
  useRegistry: true

defaults:
  app: echo
  version: 0.1
  sdk: go:1.8
  target: $target
  serviceTarget: $serviceTarget
  appTarget: $appTarget
pipeline:
  init:
    app:
      action: run
      request: "@app"
      tasks: "*"
  test:
    action: run
    name: regresion
    tasks: "*"
  destroy:
    app:
      action: run
      request: "@app"
      tasks: stop
