tasks: $tasks

init:
  buildTarget:
    URL: scp://127.0.0.1/tmp/build/sso/
    credentials: localhost

  appTarget:
    URL: scp://127.0.0.1/opt/sso/
    credentials: localhost

  target:
    URL: scp://127.0.0.1/
    credentials: localhost

defaults:
  target: $target

pipeline:


  build:
    checkout:
      action: version/control:checkout
      origin:
        URL: ./../
      dest: $buildTarget
    set-sdk:
      action: sdk:set
      sdk: go:1.12
    build-app:
      action: exec:run
      commands:
        - cd /tmp/build/sso/app
        - go build sso.go
        - chmod +x sso
    deploy:
      mkdir:
       action: exec:run
       commands:
         - sudo rm -rf /opt/sso/
         - sudo mkdir -p /opt/sso
         - sudo chown -R ${os.user} /opt/sso

      install:
        action: storage:copy
        source: $buildTarget
        dest: $appTarget
        assets:
          app/sso: sso
          config/config.json: config.json
          static: static

  stop:
    action: process:stop
    input: sso

  start:
    action: process:start
    directory: /opt/sso
    immuneToHangups: true
    command: ./sso
    arguments:
      - "-config"
      - "config.json"