tasks: $tasks
pipeline:
  destroy:
    action: docker:stop
    images:
      - aerospike
      - memcached
  init:
    config:
      action: storage:copy
      assets:
        config/aerospike.conf: /tmp/mydb1.conf

    services:
      aerospike:
        action: docker:run
        image: 'aerospike/aerospike-server:3.16.0.6'
        name: mydb1
        mount:
          /tmp/mydb1.conf: /opt/aerospike/etc/aerospike.conf
        ports:
          3000: 3000
          3001: 3001
          3002: 3002
          3003: 3003
          8081: 8081
        cmd:
          - asd
          - --config-file
          - /opt/aerospike/etc/aerospike.conf
        entrypoint:
          - /entrypoint.sh

      memcached:
        action: docker:run
        name: myCache
        image: library/memcached:alpine
        hostConfig:
          memory: 536870912

      iplookup:
        action: http/endpoint:listen
        port: 8383
        rotate: true
        baseDirectory: ipinfo/


  selenium:
    action: deployment:deploy
    target: $target
    baseLocation: /opt/
    appName: selenium-server-standalone
    version: 3.4

  geckodriver:
    action: deployment:deploy
    target: $target
    baseLocation: /opt/
    appName: geckodriver
